import { version as vueVersion } from 'vue';

import '../css/laravel-blocks.css';
import {
  BlockInserter,
  BlockInspector,
  BlockToolbar,
  SlashCommandMenu,
  blockManifestDefinition,
  blockFrameStyle,
  blockInsertPayload,
  blockInserterItems,
  blockRect,
  blockToolbarStyle,
  coerceInspectorFieldValue,
  createBlockSelectionState,
  createEmptyBlockSelection,
  filterBlockInserterItems,
  inspectorFieldValue,
  inspectorFieldsForBlock,
  inspectorGroups,
  normalizeEditorManifest,
  slashCommandItems,
  slashCommandStyle,
} from './block-editor/index.js';
import {
  bootWhenReady,
  mountLaravelBlocksEditor,
  mountLaravelBlocksEditors,
  readEditorPayload,
} from './editor/mount.js';
import {
  Button,
  Icon,
  IconButton,
  Popover,
  Toolbar,
  ToolbarGroup,
  blockIconName,
  computePopoverStyle,
  createOverlayController,
  createPopoverController,
  iconPath,
  Modal,
  normalizePopoverPlacement,
  targetIsInside,
} from './ui/index.js';
import {
  MediaClientError,
  MediaLibrary,
  createMediaClient,
  normalizeCapabilities,
  normalizeMediaItem,
  normalizeMediaTransport,
} from './media/index.js';
import { CommandRegistry, createDefaultCommandRegistry } from './editor/commands.js';
import {
  emptyDocument,
  normalizeDocument,
  toCanonicalDocument,
  toCanonicalJson,
  toTiptapDocument,
} from './editor/document.js';
import { HistoryToolbar } from './editor/HistoryToolbar.js';
import { handleHistoryShortcut, historyShortcutCommand } from './editor/keyboard-shortcuts.js';
import { createSelectionState } from './editor/selection.js';
import {
  LinkPopover,
  createRichTextToolbarItems,
  createDefaultLinkProvider,
  currentLinkForm,
  linkAttributes,
  linkErrorMessage,
  normalizeLinkHref,
  richTextToolbarCommands,
  richTextToolbarStyle,
  richTextToolbarVisible,
  runRichTextToolbarCommand,
  selectionAnchorRect,
  validateLinkHref,
} from './rich-text/index.js';

export const packageMetadata = Object.freeze({
  name: '@katonfajar/laravel-blocks',
  vueMajor: Number.parseInt(vueVersion.split('.')[0], 10),
  vueVersion,
});

export {
  BlockInserter,
  BlockInspector,
  BlockToolbar,
  SlashCommandMenu,
  blockManifestDefinition,
  bootWhenReady,
  blockFrameStyle,
  blockInsertPayload,
  blockInserterItems,
  blockRect,
  blockToolbarStyle,
  Button,
  CommandRegistry,
  coerceInspectorFieldValue,
  createBlockSelectionState,
  IconButton,
  Icon,
  blockIconName,
  iconPath,
  LinkPopover,
  MediaClientError,
  MediaLibrary,
  Modal,
  Popover,
  Toolbar,
  ToolbarGroup,
  computePopoverStyle,
  createDefaultCommandRegistry,
  createDefaultLinkProvider,
  createMediaClient,
  createEmptyBlockSelection,
  createOverlayController,
  createPopoverController,
  createRichTextToolbarItems,
  createSelectionState,
  currentLinkForm,
  emptyDocument,
  filterBlockInserterItems,
  handleHistoryShortcut,
  historyShortcutCommand,
  HistoryToolbar,
  inspectorFieldValue,
  inspectorFieldsForBlock,
  inspectorGroups,
  linkAttributes,
  linkErrorMessage,
  mountLaravelBlocksEditor,
  mountLaravelBlocksEditors,
  normalizeLinkHref,
  normalizeCapabilities,
  normalizeEditorManifest,
  normalizeMediaItem,
  normalizeMediaTransport,
  normalizePopoverPlacement,
  normalizeDocument,
  richTextToolbarCommands,
  richTextToolbarStyle,
  richTextToolbarVisible,
  readEditorPayload,
  runRichTextToolbarCommand,
  selectionAnchorRect,
  slashCommandItems,
  slashCommandStyle,
  targetIsInside,
  toCanonicalDocument,
  toCanonicalJson,
  toTiptapDocument,
  validateLinkHref,
};

export const LaravelBlocks = Object.freeze({
  packageMetadata,
  bootWhenReady,
  mountEditor: mountLaravelBlocksEditor,
  mountEditors: mountLaravelBlocksEditors,
  normalizeDocument,
  ui: Object.freeze({
    Button,
    Icon,
    IconButton,
    Modal,
    Popover,
    Toolbar,
    ToolbarGroup,
    blockIconName,
    computePopoverStyle,
    createOverlayController,
    createPopoverController,
    iconPath,
    normalizePopoverPlacement,
    targetIsInside,
  }),
  media: Object.freeze({
    MediaClientError,
    MediaLibrary,
    createMediaClient,
    normalizeCapabilities,
    normalizeMediaItem,
    normalizeMediaTransport,
  }),
  blockEditor: Object.freeze({
    BlockInserter,
    BlockInspector,
    BlockToolbar,
    SlashCommandMenu,
    blockManifestDefinition,
    blockFrameStyle,
    blockInsertPayload,
    blockInserterItems,
    blockRect,
    blockToolbarStyle,
    coerceInspectorFieldValue,
    createBlockSelectionState,
    createEmptyBlockSelection,
    filterBlockInserterItems,
    inspectorFieldValue,
    inspectorFieldsForBlock,
    inspectorGroups,
    normalizeEditorManifest,
    slashCommandItems,
    slashCommandStyle,
  }),
  richText: Object.freeze({
    LinkPopover,
    createRichTextToolbarItems,
    createDefaultLinkProvider,
    currentLinkForm,
    linkAttributes,
    linkErrorMessage,
    normalizeLinkHref,
    richTextToolbarCommands,
    richTextToolbarStyle,
    richTextToolbarVisible,
    runRichTextToolbarCommand,
    selectionAnchorRect,
    validateLinkHref,
  }),
  toCanonicalDocument,
  toCanonicalJson,
});

if (typeof window !== 'undefined') {
  window.LaravelBlocks = LaravelBlocks;
  bootWhenReady();
}
